//! Session/context commands: `/init`, `/resume`, `/recap`, `/btw`.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;

use super::{SlashCommand, SlashCommandMeta, SlashCommandRegistry, SlashCtx, SlashOutcome};
use crate::tui::TranscriptLine;

/// `/init` — generate a starter `CLAUDE.draft.md` from available context.
///
/// Sources, in priority order: `AGENTS.md`, `.cursorrules`,
/// `.windsurfrules`, `README.md`, current `git status --short`.
///
/// Refuses to overwrite an existing `CLAUDE.md` without `--force`;
/// default behavior is to write `CLAUDE.draft.md`.
pub(crate) struct InitCommand;

#[async_trait]
impl SlashCommand for InitCommand {
    fn meta(&self) -> &SlashCommandMeta {
        &SlashCommandMeta {
            name: "/init",
            description: "generate a CLAUDE.draft.md from AGENTS.md / cursorrules / git status",
            args_hint: "[--force]",
            hidden: false,
            immediate: true,
        }
    }
    async fn execute(&self, args: &str, ctx: &mut SlashCtx<'_>) -> Result<SlashOutcome> {
        let kv = super::parse_kv_args(args);
        let force = kv.contains_key("force");
        let root = ctx
            .app
            .args
            .workspace
            .clone()
            .unwrap_or_else(|| ctx.app.cwd.clone());
        let draft_path = root.join("CLAUDE.draft.md");
        let claude_md = root.join("CLAUDE.md");
        if claude_md.exists() && !force {
            ctx.app.transcript.push(TranscriptLine::Info(format!(
                "CLAUDE.md already exists at {} \u{2014} writing draft to {}",
                claude_md.display(),
                draft_path.display(),
            )));
        }
        let body = init::compose_draft(&root);
        match std::fs::write(&draft_path, &body) {
            Ok(()) => {
                ctx.app.transcript.push(TranscriptLine::Info(format!(
                    "wrote {} ({} bytes); review and rename to CLAUDE.md",
                    draft_path.display(),
                    body.len(),
                )));
            }
            Err(e) => {
                ctx.app
                    .transcript
                    .push(TranscriptLine::Error(format!("/init: {e}")));
            }
        }
        Ok(SlashOutcome::Continue)
    }
}

pub(crate) mod init {
    //! Pure helpers for `/init` so the draft composer is unit-testable
    //! without an `App`.
    use std::path::Path;

    /// Compose a draft `CLAUDE.md` from whatever sources exist under `root`.
    /// Sections are skipped silently if their source isn't present.
    #[must_use]
    pub(crate) fn compose_draft(root: &Path) -> String {
        use std::fmt::Write as _;
        let mut out = String::from("# CLAUDE.md (draft)\n\n");
        out.push_str("Generated by `/init`. Review, edit, then rename to `CLAUDE.md`.\n\n");

        for (label, name) in [
            ("AGENTS.md", "AGENTS.md"),
            (".cursorrules", ".cursorrules"),
            (".windsurfrules", ".windsurfrules"),
            ("README.md", "README.md"),
        ] {
            let path = root.join(name);
            if let Ok(contents) = std::fs::read_to_string(&path) {
                // `write!` into a String is infallible.
                let _ = writeln!(out, "## from {label}\n");
                out.push_str(contents.trim());
                out.push_str("\n\n");
            }
        }

        if let Some(status) = git_status(root) {
            out.push_str("## git status\n\n```\n");
            out.push_str(&status);
            out.push_str("```\n\n");
        }

        out
    }

    fn git_status(root: &Path) -> Option<String> {
        let out = std::process::Command::new("git")
            .args(["-C", &root.to_string_lossy(), "status", "--short"])
            .output()
            .ok()?;
        if !out.status.success() {
            return None;
        }
        Some(String::from_utf8_lossy(&out.stdout).into_owned())
    }
}

/// `/resume [query]` — list persisted sessions sorted by mtime, with
/// an optional case-insensitive substring filter on the session name.
/// The full overlay picker (Up/Down/Enter to swap session in place)
/// is deferred until the Overlay enum gains a non-Copy variant; until
/// then this command emits the matching list inline so the operator
/// can paste a name into `caliban --session <name>`.
pub(crate) struct ResumeCommand;

#[async_trait]
impl SlashCommand for ResumeCommand {
    fn meta(&self) -> &SlashCommandMeta {
        &SlashCommandMeta {
            name: "/resume",
            description: "list persisted sessions (optional substring filter)",
            args_hint: "[query]",
            hidden: false,
            immediate: true,
        }
    }
    async fn execute(&self, args: &str, ctx: &mut SlashCtx<'_>) -> Result<SlashOutcome> {
        let query = args.trim().to_ascii_lowercase();
        match ctx.app.store.as_ref() {
            None => {
                ctx.app
                    .transcript
                    .push(TranscriptLine::Info("no session store configured".into()));
            }
            Some(store) => match store.list() {
                Ok(list) if list.is_empty() => {
                    ctx.app
                        .transcript
                        .push(TranscriptLine::Info("no sessions yet".into()));
                }
                Ok(mut list) => {
                    list.sort_by_key(|m| std::cmp::Reverse(m.updated_at));
                    let total = list.len();
                    let filtered: Vec<_> = list
                        .into_iter()
                        .filter(|m| {
                            query.is_empty() || m.name.to_ascii_lowercase().contains(&query)
                        })
                        .collect();
                    if filtered.is_empty() {
                        ctx.app.transcript.push(TranscriptLine::Info(format!(
                            "{total} session(s); 0 match `{query}`"
                        )));
                    } else {
                        let header = if query.is_empty() {
                            format!("{} session(s) (newest first):", filtered.len())
                        } else {
                            format!("{} of {total} session(s) match `{query}`:", filtered.len())
                        };
                        ctx.app.transcript.push(TranscriptLine::Info(header));
                        for m in filtered {
                            ctx.app.transcript.push(TranscriptLine::Info(format!(
                                "  {} \u{2014} {} turns, {} tokens \u{2014} {}",
                                m.name,
                                m.turn_count,
                                m.total_tokens,
                                m.updated_at.format("%Y-%m-%d %H:%M:%S"),
                            )));
                        }
                        ctx.app.transcript.push(TranscriptLine::Info(
                            "full overlay picker (in-place swap) lands in a follow-up".into(),
                        ));
                    }
                }
                Err(e) => {
                    ctx.app
                        .transcript
                        .push(TranscriptLine::Error(format!("list error: {e}")));
                }
            },
        }
        Ok(SlashOutcome::Continue)
    }
}

/// `/recap` — run the configured Compactor against the current history and
/// emit the summary as a user-visible message (does not modify history).
pub(crate) struct RecapCommand;

#[async_trait]
impl SlashCommand for RecapCommand {
    fn meta(&self) -> &SlashCommandMeta {
        &SlashCommandMeta {
            name: "/recap",
            description: "summarize the conversation so far without mutating history",
            args_hint: "",
            hidden: false,
            immediate: false,
        }
    }
    async fn execute(&self, _args: &str, ctx: &mut SlashCtx<'_>) -> Result<SlashOutcome> {
        if ctx.app.messages.is_empty() {
            ctx.app
                .transcript
                .push(TranscriptLine::Info("recap: no messages yet".into()));
            return Ok(SlashOutcome::Continue);
        }
        let model = ctx.app.args.model.clone().unwrap_or_else(|| {
            crate::default_model_for(crate::resolved_provider(&ctx.app.args)).to_string()
        });
        let caps = ctx.app.agent.provider().capabilities(&model);
        let compactor = ctx.app.agent.compactor();
        let messages = ctx.app.messages.clone();
        let result = compactor.compact(&messages, &caps).await;
        match result {
            Err(e) => {
                ctx.app
                    .transcript
                    .push(TranscriptLine::Error(format!("recap failed: {e}")));
            }
            Ok(None) => {
                ctx.app.transcript.push(TranscriptLine::Info(format!(
                    "recap: nothing to summarize (strategy {})",
                    compactor.strategy_name()
                )));
            }
            Ok(Some(new)) => {
                ctx.app.transcript.push(TranscriptLine::Info(format!(
                    "recap (strategy {}) \u{2014} {} message(s) summarized:",
                    compactor.strategy_name(),
                    messages.len().saturating_sub(new.len()),
                )));
                // Extract any system summary text the compactor produced
                // and inline it as Info lines.
                for msg in &new {
                    for block in &msg.content {
                        if let caliban_provider::ContentBlock::Text(tb) = block {
                            for line in tb.text.lines() {
                                ctx.app
                                    .transcript
                                    .push(TranscriptLine::Info(line.to_string()));
                            }
                        }
                    }
                }
            }
        }
        Ok(SlashOutcome::Continue)
    }
}

/// `/btw` — one-shot ephemeral side question against a fast model
/// (Haiku/`FastClassifier`). Doesn't touch the main session.
pub(crate) struct BtwCommand;

#[async_trait]
impl SlashCommand for BtwCommand {
    fn meta(&self) -> &SlashCommandMeta {
        &SlashCommandMeta {
            name: "/btw",
            description: "one-shot ephemeral question to a fast model; result inlined",
            args_hint: "<question>",
            hidden: false,
            immediate: false,
        }
    }
    async fn execute(&self, args: &str, ctx: &mut SlashCtx<'_>) -> Result<SlashOutcome> {
        let q = args.trim();
        if q.is_empty() {
            ctx.app.transcript.push(TranscriptLine::Info(
                "usage: /btw <question> \u{2014} runs a one-shot side query".into(),
            ));
            return Ok(SlashOutcome::Continue);
        }
        let model = ctx.app.args.model.clone().unwrap_or_else(|| {
            crate::default_model_for(crate::resolved_provider(&ctx.app.args)).to_string()
        });
        let provider = ctx.app.agent.provider();
        let req = btw::build_request(&model, q);
        match provider.complete(req).await {
            Ok(resp) => {
                let text = btw::extract_text(&resp.message.content);
                ctx.app
                    .transcript
                    .push(TranscriptLine::Info(format!("btw \u{2014} {text}")));
            }
            Err(e) => {
                ctx.app
                    .transcript
                    .push(TranscriptLine::Error(format!("/btw failed: {e}")));
            }
        }
        Ok(SlashOutcome::Continue)
    }
}

pub(crate) mod btw {
    //! Helpers for `/btw`, pulled out for unit testing.
    use caliban_provider::{
        CompletionRequest, ContentBlock, Message, RequestMetadata, RequestPurpose,
    };

    /// Concatenate the `Text` blocks of a response into a single string.
    #[must_use]
    pub(crate) fn extract_text(blocks: &[ContentBlock]) -> String {
        let mut out = String::new();
        for block in blocks {
            if let ContentBlock::Text(tb) = block {
                if !out.is_empty() {
                    out.push('\n');
                }
                out.push_str(&tb.text);
            }
        }
        out
    }

    /// Build the one-shot request for `/btw`. The `purpose` field is
    /// stamped `FastClassifier` so the model router (when present) picks
    /// a fast model. Pulled out so the request shape is unit-testable
    /// without a live provider.
    #[must_use]
    pub(crate) fn build_request(model: &str, question: &str) -> CompletionRequest {
        CompletionRequest {
            model: model.to_string(),
            messages: vec![Message::user_text(question)],
            tools: vec![],
            tool_choice: caliban_provider::ToolChoice::default(),
            max_tokens: 512,
            temperature: None,
            top_p: None,
            top_k: None,
            stop_sequences: vec![],
            thinking: caliban_provider::ThinkingSetting::Auto,
            effort: None,
            metadata: RequestMetadata {
                user_id: None,
                purpose: Some(RequestPurpose::FastClassifier),
            },
        }
    }
}

pub(crate) fn register(registry: &mut SlashCommandRegistry) {
    registry.register(Arc::new(InitCommand));
    registry.register(Arc::new(ResumeCommand));
    registry.register(Arc::new(RecapCommand));
    registry.register(Arc::new(BtwCommand));
}

#[cfg(test)]
mod resume_tests {
    use super::*;
    use crate::tui::app::App;

    fn seed_store(app: &mut App, names: &[&str]) {
        let tmp = tempfile::tempdir().unwrap();
        let store = caliban_sessions::SessionStore::new(tmp.path().to_path_buf());
        for name in names {
            let sess = caliban_sessions::PersistedSession::new(*name, "mock", "mock");
            store.save(&sess).unwrap();
        }
        store.flush();
        app.store = Some(store);
        // Leak the tempdir so files live as long as the test.
        std::mem::forget(tmp);
    }

    #[tokio::test]
    async fn resume_with_no_query_lists_all() {
        let mut app = App::for_tests();
        seed_store(&mut app, &["foo", "bar", "baz"]);
        let mut ctx = app.slash_ctx_for_tests();
        let outcome = ResumeCommand.execute("", &mut ctx).await.unwrap();
        assert!(matches!(outcome, SlashOutcome::Continue));
        let body: String = app
            .transcript
            .iter()
            .filter_map(|l| match l {
                TranscriptLine::Info(s) => Some(s.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n");
        assert!(body.contains("foo"));
        assert!(body.contains("bar"));
        assert!(body.contains("baz"));
    }

    #[tokio::test]
    async fn resume_with_query_narrows_list() {
        let mut app = App::for_tests();
        seed_store(&mut app, &["foo-bar", "baz-quux", "foo-baz"]);
        let mut ctx = app.slash_ctx_for_tests();
        let _ = ResumeCommand.execute("foo", &mut ctx).await.unwrap();
        let body: String = app
            .transcript
            .iter()
            .filter_map(|l| match l {
                TranscriptLine::Info(s) => Some(s.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n");
        assert!(body.contains("foo-bar"));
        assert!(body.contains("foo-baz"));
        assert!(!body.contains("baz-quux"), "filter should drop non-match");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_compose_draft_includes_present_sources() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("AGENTS.md"), "agent rules here").unwrap();
        std::fs::write(tmp.path().join(".cursorrules"), "cursor: be terse").unwrap();
        let draft = init::compose_draft(tmp.path());
        assert!(draft.contains("# CLAUDE.md (draft)"));
        assert!(draft.contains("from AGENTS.md"));
        assert!(draft.contains("agent rules here"));
        assert!(draft.contains("from .cursorrules"));
        assert!(draft.contains("cursor: be terse"));
        // No README.md present → no README section.
        assert!(!draft.contains("from README.md"));
    }

    #[test]
    fn init_compose_draft_empty_when_no_sources() {
        let tmp = tempfile::tempdir().unwrap();
        let draft = init::compose_draft(tmp.path());
        assert!(draft.contains("# CLAUDE.md (draft)"));
        // No source sections appended.
        assert!(!draft.contains("## from"));
    }

    #[test]
    fn btw_build_request_stamps_fast_classifier_purpose() {
        let req = btw::build_request("test-model", "what time is it?");
        assert_eq!(req.model, "test-model");
        assert_eq!(req.messages.len(), 1);
        assert_eq!(
            req.metadata.purpose,
            Some(caliban_provider::RequestPurpose::FastClassifier)
        );
    }

    #[test]
    fn btw_extract_text_concatenates_text_blocks() {
        use caliban_provider::{ContentBlock, TextBlock};
        let blocks = vec![
            ContentBlock::Text(TextBlock {
                text: "Hello".into(),
                cache_control: None,
            }),
            ContentBlock::Text(TextBlock {
                text: "world".into(),
                cache_control: None,
            }),
        ];
        assert_eq!(btw::extract_text(&blocks), "Hello\nworld");
    }
}
