//! IPC wire types for the supervisor protocol.
//!
//! The wire format is newline-delimited JSON: each request is one JSON
//! object terminated by `\n`; each reply is one JSON object terminated
//! by `\n`. NDJSON keeps the protocol trivially debuggable (`nc -U` +
//! eyeball) at a small bandwidth cost we don't care about for a local
//! control plane.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::transport::Endpoint;

/// Opaque agent identifier (a 12-char ULID-like prefix). Generated by
/// the supervisor on spawn.
pub type AgentId = String;

/// Lifecycle state of a registered sub-agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentStatus {
    /// Just registered, hasn't begun executing yet.
    Spawning,
    /// Actively running (or attached).
    Running,
    /// Awaiting input; no compute pending.
    Idle,
    /// Stopped via `kill`.
    Killed,
    /// Finished successfully.
    Done,
    /// Finished with an error.
    Failed,
    /// Supervisor restarted while this agent was active; needs recovery.
    Crashed,
}

/// Snapshot describing a registered sub-agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRecord {
    /// Opaque id.
    pub id: AgentId,
    /// Human-readable label (frontmatter `label` or generated default).
    pub name: String,
    /// Current lifecycle state.
    pub status: AgentStatus,
    /// RFC-3339 timestamp of when the agent was registered.
    pub started_at: String,
    /// Path to the agent's session directory (where `session.json` etc. live).
    pub session_dir: PathBuf,
    /// Endpoint for the agent's per-agent socket (for `attach`).
    pub endpoint: Endpoint,
    /// Resolved working directory for the worker (the source dir, or its
    /// per-source worktree when `spec.isolation_worktree`). Empty = inherit
    /// the daemon's cwd (legacy records). (#281)
    #[serde(default)]
    pub working_dir: PathBuf,
    /// Original spawn spec (preserved so `respawn` can re-run).
    pub spec: SpawnSpec,
}

impl AgentRecord {
    /// The Unix socket path, when this agent is served over a Unix socket.
    pub fn unix_socket_path(&self) -> Option<&std::path::Path> {
        match &self.endpoint {
            Endpoint::Unix { path } => Some(path.as_path()),
            Endpoint::Tcp { .. } => None,
        }
    }
}

/// Daemon status returned by [`CtlRequest::Status`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaemonStatus {
    /// PID of the daemon process.
    pub pid: u32,
    /// Number of registered agents (across all states).
    pub agents: u32,
    /// Seconds since the daemon started.
    pub uptime_secs: u64,
    /// Endpoint of the control socket.
    pub endpoint: Endpoint,
}

/// Parameters for a new sub-agent spawn. The supervisor stores this so
/// `respawn` can reuse it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpawnSpec {
    /// Optional human-readable name for the agent.
    #[serde(default)]
    pub label: Option<String>,
    /// Path to the frontmatter markdown file (if any).
    #[serde(default)]
    pub frontmatter_path: Option<PathBuf>,
    /// Initial prompt handed to the sub-agent.
    pub initial_prompt: String,
    /// Optional model override.
    #[serde(default)]
    pub model: Option<String>,
    /// Optional provider override (e.g. "anthropic", "ollama", "openai",
    /// "google"). The worker parses this to select the provider; without
    /// it the worker uses caliban's default (anthropic). (#93)
    #[serde(default)]
    pub provider: Option<String>,
    /// Optional tool allowlist.
    #[serde(default)]
    pub tool_allowlist: Option<Vec<String>>,
    /// True iff the sub-agent should run in an isolated worktree.
    #[serde(default)]
    pub isolation_worktree: bool,
    /// Whether to inherit parent hooks (config-serializable portion only).
    #[serde(default = "true_default")]
    pub inherit_hooks: bool,
    /// When true, the worker runs in interactive mode: at each end-of-run
    /// boundary it awaits inbound operator messages over the per-agent
    /// socket instead of finishing (ADR 0047 / #81).
    #[serde(default)]
    pub interactive: bool,
    /// Opaque JSON-serialized parent permission config, inherited by the
    /// worker when `inherit_hooks` is true (#84). The supervisor shuttles
    /// this verbatim; only the `caliban` worker interprets it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inherited_hooks_config: Option<String>,
    /// Which workspace source (checkout) this agent runs against. `None`
    /// means the workspace root (single-source back-compat). (#281)
    #[serde(default)]
    pub source: Option<String>,
}

fn true_default() -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spawnspec_source_defaults_and_roundtrips() {
        let legacy = r#"{"initial_prompt":"hi"}"#; // no source field
        let spec: SpawnSpec = serde_json::from_str(legacy).unwrap();
        assert_eq!(spec.source, None);
        let with_src = SpawnSpec {
            source: Some("gonzalo".into()),
            ..spec
        };
        let json = serde_json::to_string(&with_src).unwrap();
        assert_eq!(
            serde_json::from_str::<SpawnSpec>(&json).unwrap().source,
            Some("gonzalo".into())
        );
    }
}

/// Control-plane requests from the CLI / parent agent to the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CtlRequest {
    /// List all registered agents.
    List,
    /// Register and start a new agent.
    Spawn {
        /// Spec describing the agent to create.
        spec: SpawnSpec,
    },
    /// Return the dedicated socket for an agent so the caller can attach.
    Attach {
        /// Target agent.
        id: AgentId,
    },
    /// Terminate an agent (SIGTERM, escalating to SIGKILL after the
    /// configured grace).
    Kill {
        /// Target agent.
        id: AgentId,
    },
    /// Kill + re-spawn with the same spec.
    Respawn {
        /// Target agent.
        id: AgentId,
    },
    /// Remove an agent from the registry (must already be stopped unless
    /// `force` is set).
    Rm {
        /// Target agent.
        id: AgentId,
        /// Force-remove even if the agent is still running.
        #[serde(default)]
        force: bool,
    },
    /// Daemon health probe.
    Status,
    /// Ask the daemon to mark itself for shutdown after the current
    /// in-flight requests complete.
    Shutdown,
    /// A worker reports a lifecycle transition (Running <-> Idle) for itself.
    ReportStatus {
        /// Reporting agent.
        id: AgentId,
        /// New status (only Running/Idle are honored; see registry guard).
        status: AgentStatus,
    },
}

/// Control-plane replies.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CtlReply {
    /// Successful list response.
    Listed {
        /// Registered agents.
        agents: Vec<AgentRecord>,
    },
    /// Successful spawn.
    Spawned {
        /// Newly assigned id.
        id: AgentId,
        /// Per-agent endpoint the caller can attach to.
        endpoint: Endpoint,
    },
    /// Successful attach handshake (the per-agent endpoint is also
    /// returned here for backwards-compat with `attach <id>`).
    AttachAck {
        /// Per-agent endpoint.
        endpoint: Endpoint,
    },
    /// Successful kill.
    Killed,
    /// Successful respawn — new id assigned.
    Respawned {
        /// New id (old id is removed).
        id: AgentId,
    },
    /// Successful rm.
    Removed,
    /// Daemon status snapshot.
    Status(DaemonStatus),
    /// Daemon will shut down once it's drained.
    ShutdownAck,
    /// Acknowledged a status report.
    StatusReported,
    /// An error occurred.
    Error {
        /// Structured error variant.
        error: SupervisorError,
    },
}

/// Errors the supervisor reports back to clients.
#[derive(thiserror::Error, Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SupervisorError {
    /// No such agent.
    #[error("agent not found: {id}")]
    NotFound {
        /// Missing id.
        id: AgentId,
    },
    /// Agent is in the wrong state for the requested operation.
    #[error("invalid state for {op}: agent {id} is {status:?}")]
    InvalidState {
        /// Operation attempted.
        op: String,
        /// Target id.
        id: AgentId,
        /// Actual status.
        status: AgentStatus,
    },
    /// Daemon hit a generic internal error.
    #[error("internal supervisor error: {message}")]
    Internal {
        /// Free-form message.
        message: String,
    },
}
