//! IPC wire types for the supervisor protocol.
//!
//! The wire format is newline-delimited JSON: each request is one JSON
//! object terminated by `\n`; each reply is one JSON object terminated
//! by `\n`. NDJSON keeps the protocol trivially debuggable (`nc -U` +
//! eyeball) at a small bandwidth cost we don't care about for a local
//! control plane.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Opaque agent identifier (a 12-char ULID-like prefix). Generated by
/// the supervisor on spawn.
pub type AgentId = String;

/// Lifecycle state of a registered sub-agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentStatus {
    /// Just registered, hasn't begun executing yet.
    Spawning,
    /// Actively running (or attached).
    Running,
    /// Awaiting input; no compute pending.
    Idle,
    /// Stopped via `kill`.
    Killed,
    /// Finished successfully.
    Done,
    /// Finished with an error.
    Failed,
    /// Supervisor restarted while this agent was active; needs recovery.
    Crashed,
}

/// Snapshot describing a registered sub-agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRecord {
    /// Opaque id.
    pub id: AgentId,
    /// Human-readable label (frontmatter `label` or generated default).
    pub name: String,
    /// Current lifecycle state.
    pub status: AgentStatus,
    /// RFC-3339 timestamp of when the agent was registered.
    pub started_at: String,
    /// Path to the agent's session directory (where `session.json` etc. live).
    pub session_dir: PathBuf,
    /// Path to the agent's per-agent socket (for `attach`).
    pub socket_path: PathBuf,
    /// Original spawn spec (preserved so `respawn` can re-run).
    pub spec: SpawnSpec,
}

/// Daemon status returned by [`CtlRequest::Status`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaemonStatus {
    /// PID of the daemon process.
    pub pid: u32,
    /// Number of registered agents (across all states).
    pub agents: u32,
    /// Seconds since the daemon started.
    pub uptime_secs: u64,
    /// Path to the control socket.
    pub socket_path: PathBuf,
}

/// Parameters for a new sub-agent spawn. The supervisor stores this so
/// `respawn` can reuse it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpawnSpec {
    /// Optional human-readable name for the agent.
    #[serde(default)]
    pub label: Option<String>,
    /// Path to the frontmatter markdown file (if any).
    #[serde(default)]
    pub frontmatter_path: Option<PathBuf>,
    /// Initial prompt handed to the sub-agent.
    pub initial_prompt: String,
    /// Optional model override.
    #[serde(default)]
    pub model: Option<String>,
    /// Optional tool allowlist.
    #[serde(default)]
    pub tool_allowlist: Option<Vec<String>>,
    /// True iff the sub-agent should run in an isolated worktree.
    #[serde(default)]
    pub isolation_worktree: bool,
    /// Whether to inherit parent hooks (config-serializable portion only).
    #[serde(default = "true_default")]
    pub inherit_hooks: bool,
}

fn true_default() -> bool {
    true
}

/// Control-plane requests from the CLI / parent agent to the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CtlRequest {
    /// List all registered agents.
    List,
    /// Register and start a new agent.
    Spawn {
        /// Spec describing the agent to create.
        spec: SpawnSpec,
    },
    /// Return the dedicated socket for an agent so the caller can attach.
    Attach {
        /// Target agent.
        id: AgentId,
    },
    /// Terminate an agent (SIGTERM, escalating to SIGKILL after the
    /// configured grace).
    Kill {
        /// Target agent.
        id: AgentId,
    },
    /// Kill + re-spawn with the same spec.
    Respawn {
        /// Target agent.
        id: AgentId,
    },
    /// Remove an agent from the registry (must already be stopped unless
    /// `force` is set).
    Rm {
        /// Target agent.
        id: AgentId,
        /// Force-remove even if the agent is still running.
        #[serde(default)]
        force: bool,
    },
    /// Daemon health probe.
    Status,
    /// Ask the daemon to mark itself for shutdown after the current
    /// in-flight requests complete.
    Shutdown,
}

/// Control-plane replies.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CtlReply {
    /// Successful list response.
    Listed {
        /// Registered agents.
        agents: Vec<AgentRecord>,
    },
    /// Successful spawn.
    Spawned {
        /// Newly assigned id.
        id: AgentId,
        /// Per-agent socket the caller can attach to.
        socket_path: PathBuf,
    },
    /// Successful attach handshake (the per-agent socket path is also
    /// returned here for backwards-compat with `attach <id>`).
    AttachAck {
        /// Per-agent socket path.
        socket_path: PathBuf,
    },
    /// Successful kill.
    Killed,
    /// Successful respawn — new id assigned.
    Respawned {
        /// New id (old id is removed).
        id: AgentId,
    },
    /// Successful rm.
    Removed,
    /// Daemon status snapshot.
    Status(DaemonStatus),
    /// Daemon will shut down once it's drained.
    ShutdownAck,
    /// An error occurred.
    Error {
        /// Structured error variant.
        error: SupervisorError,
    },
}

/// Errors the supervisor reports back to clients.
#[derive(thiserror::Error, Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SupervisorError {
    /// No such agent.
    #[error("agent not found: {id}")]
    NotFound {
        /// Missing id.
        id: AgentId,
    },
    /// Agent is in the wrong state for the requested operation.
    #[error("invalid state for {op}: agent {id} is {status:?}")]
    InvalidState {
        /// Operation attempted.
        op: String,
        /// Target id.
        id: AgentId,
        /// Actual status.
        status: AgentStatus,
    },
    /// Daemon hit a generic internal error.
    #[error("internal supervisor error: {message}")]
    Internal {
        /// Free-form message.
        message: String,
    },
}
