//! Native wire-format types for `OpenAI` streaming SSE chunks.

use serde::{Deserialize, Serialize};

pub use crate::schema::response::NativeFinishReason;

/// A single SSE chunk from a streaming `POST /chat/completions` response.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NativeChunk {
    /// Unique response identifier shared across chunks.
    pub id: String,
    /// The model that generated the response.
    pub model: String,
    /// Choices array; for `n=1` there is always exactly one element.
    pub choices: Vec<NativeChunkChoice>,
    /// Token usage; only present in the final chunk when
    /// `stream_options.include_usage = true` was sent.
    #[serde(default)]
    pub usage: Option<NativeUsageDelta>,
}

/// A single choice element within a streaming chunk.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NativeChunkChoice {
    /// The choice index (always 0 for `n=1`).
    pub index: u32,
    /// The incremental delta for this chunk.
    pub delta: NativeDelta,
    /// Present on the final chunk for this choice.
    #[serde(default)]
    pub finish_reason: Option<NativeFinishReason>,
}

/// The delta payload within a streaming chunk choice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NativeDelta {
    /// Present on the very first chunk (`"assistant"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Incremental text content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Incremental tool-call deltas.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<NativeDeltaToolCall>,
    /// Refusal text from the model's safety layer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refusal: Option<String>,
}

/// An incremental tool-call fragment within a streaming delta.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NativeDeltaToolCall {
    /// The index of this tool call in the `tool_calls` array (stable across chunks).
    pub index: u32,
    /// Present only on the first chunk for this tool call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The function fragment (name on first chunk, arguments accumulate).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<NativeDeltaFunction>,
}

/// The function portion of a streaming tool-call delta.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct NativeDeltaFunction {
    /// Present only on the first chunk for this tool call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Accumulating arguments JSON fragment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

/// Token usage reported in the final streaming chunk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct NativeUsageDelta {
    /// Tokens consumed by the prompt.
    pub prompt_tokens: u32,
    /// Tokens generated by the completion.
    pub completion_tokens: u32,
    /// Total tokens (prompt + completion).
    #[serde(default)]
    pub total_tokens: u32,
    /// Breakdown of prompt token categories.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<NativeUsageDeltaPromptDetails>,
}

/// Breakdown of prompt token categories within the usage delta.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct NativeUsageDeltaPromptDetails {
    /// Tokens served from the prompt cache.
    pub cached_tokens: u32,
}
